name:                aes
version:             0.1.0.0
github:              "dmvianna/aes"
license:             BSD3
author:              "Daniel Vianna"
maintainer:          "1708810+dmvianna@users.noreply.github.com"
copyright:           "2023 Daniel Vianna"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Small experiment with AES encryption
# category:            Experiment

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/dmvianna/aes#readme>

dependencies:
- base >= 4.7 && < 5
- memory
- bytestring
- cryptonite >=0.3.0

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints


library:
  source-dirs: src
  exposed-modules: Lib
  other-modules: []

executables:
  aes-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aes
    other-modules: []

tests:
  aes-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aes
    - file-embed
    - hspec
    - HUnit
    other-modules: []
